import { random } from '../apps/common/utils';
import { PrimaryDatabase } from '../apps/paladin/shared/database/PrimaryDatabase';
import { UserEntity } from '../apps/paladin/entities/UserEntity';

const firstNames = [
  'James',
  'Mary',
  'John',
  'Patricia',
  'Robert',
  'Jennifer',
  'Michael',
  'Linda',
  'William',
  'Elizabeth',
  'David',
  'Barbara',
  'Richard',
  'Susan',
  'Joseph',
  'Jessica',
  'Thomas',
  'Sarah',
  'Christopher',
  'Karen',
  'Daniel',
  'Nancy',
  'Matthew',
  'Lisa',
  'Anthony',
  'Betty',
  'Mark',
  'Margaret',
  'Donald',
  'Sandra',
  'Steven',
  'Ashley',
  'Paul',
  'Kimberly',
  'Andrew',
  'Emily',
  'Joshua',
  'Donna',
  'Kenneth',
  'Michelle',
  'Kevin',
  'Dorothy',
  'Brian',
  'Carol',
  'George',
  'Amanda',
  'Edward',
  'Melissa',
  'Ronald',
  'Deborah',
  'Timothy',
  'Stephanie',
  'Jason',
  'Rebecca',
  'Jeffrey',
  'Sharon',
  'Ryan',
  'Laura',
  'Jacob',
  'Cynthia',
  'Gary',
  'Kathleen',
  'Nicholas',
  'Amy',
  'Eric',
  'Angela',
  'Jonathan',
  'Shirley',
  'Stephen',
  'Anna',
  'Larry',
  'Brenda',
  'Justin',
  'Pamela',
  'Scott',
  'Emma',
  'Brandon',
  'Nicole',
  'Benjamin',
  'Helen',
  'Samuel',
  'Samantha',
  'Frank',
  'Katherine',
  'Gregory',
  'Christine',
  'Raymond',
  'Debra',
  'Alexander',
  'Rachel',
  'Patrick',
  'Carolyn',
  'Jack',
  'Janet',
  'Dennis',
  'Catherine',
  'Jerry',
  'Maria',
  'Tyler',
  'Heather',
  'Aaron',
  'Diane',
  'Jose',
  'Julie',
  'Henry',
  'Joyce',
  'Adam',
  'Victoria',
  'Douglas',
  'Kelly',
  'Nathan',
  'Christina',
  'Zachary',
  'Joan',
  'Kyle',
  'Evelyn',
  'Noah',
  'Judith',
  'Ethan',
  'Megan',
  'Jeremy',
  'Cheryl',
  'Walter',
  'Andrea',
  'Christian',
  'Hannah',
  'Keith',
  'Jacqueline',
  'Roger',
  'Martha',
  'Terry',
  'Gloria',
  'Gerald',
  'Teresa',
  'Harold',
  'Sara',
  'Sean',
  'Janice',
  'Austin',
  'Marie',
  'Carl',
  'Julia',
  'Arthur',
  'Grace',
  'Lawrence',
  'Judy',
  'Dylan',
  'Theresa',
  'Jesse',
  'Madison',
  'Jordan',
  'Beverly',
  'Bryan',
  'Denise',
  'Billy',
  'Marilyn',
  'Joe',
  'Amber',
  'Bruce',
  'Danielle',
  'Gabriel',
  'Rose',
  'Logan',
  'Brittany',
  'Albert',
  'Diana',
  'Willie',
  'Abigail',
  'Alan',
  'Jane',
  'Juan',
  'Lori',
  'Wayne',
  'Alexis',
  'Roy',
  'Marie',
  'Ralph',
  'Olivia',
  'Randy',
  'Carla',
  'Eugene',
  'Tammy',
  'Vincent',
  'Andrea',
  'Russell',
  'Annie',
  'Elijah',
  'Brittany',
  'Louis',
  'Lauren',
  'Bobby',
  'Emma',
  'Philip',
  'Megan',
  'Johnny',
  'Alicia',
  'Howard',
  'Suzanne',
];

const lastNames = [
  'Smith',
  'Johnson',
  'Williams',
  'Brown',
  'Jones',
  'Garcia',
  'Miller',
  'Davis',
  'Rodriguez',
  'Martinez',
  'Hernandez',
  'Lopez',
  'Wilson',
  'Anderson',
  'Thomas',
  'Taylor',
  'Moore',
  'Jackson',
  'Martin',
  'Lee',
  'Thompson',
  'White',
  'Harris',
  'Sanchez',
  'Clark',
  'Ramirez',
  'Lewis',
  'Robinson',
  'Walker',
  'Young',
  'Allen',
  'King',
  'Wright',
  'Scott',
  'Torres',
  'Nguyen',
  'Hill',
  'Flores',
  'Green',
  'Adams',
  'Nelson',
  'Baker',
  'Hall',
  'Rivera',
  'Campbell',
  'Mitchell',
  'Carter',
  'Roberts',
  'Gomez',
  'Phillips',
  'Evans',
  'Turner',
  'Diaz',
  'Parker',
  'Cruz',
  'Edwards',
  'Collins',
  'Reyes',
  'Stewart',
  'Morris',
  'Morales',
  'Murphy',
  'Cook',
  'Rogers',
  'Gutierrez',
  'Ortiz',
  'Morgan',
  'Cooper',
  'Peterson',
  'Bailey',
  'Reed',
  'Kelly',
  'Howard',
  'Ramos',
  'Kim',
  'Cox',
  'Ward',
  'Richardson',
  'Watson',
  'Brooks',
  'Chavez',
  'Wood',
  'James',
  'Bennett',
  'Gray',
  'Mendoza',
  'Ruiz',
  'Hughes',
  'Price',
  'Alvarez',
  'Castillo',
  'Sanders',
  'Patel',
  'Myers',
  'Long',
  'Ross',
  'Foster',
  'Jimenez',
];

function getRandomElement<T>(array: T[]): T {
  return array[Math.floor(Math.random() * array.length)]!;
}

function generateEmail(firstName: string, lastName: string): string {
  const domains = [
    'gmail.com',
    'yahoo.com',
    'outlook.com',
    'hotmail.com',
    'icloud.com',
    'protonmail.com',
    'company.com',
    'example.com',
  ];
  const domain = getRandomElement(domains);
  const number = Math.random() < 0.3 ? Math.floor(Math.random() * 1000) : '';
  return `${firstName.toLowerCase()}.${lastName.toLowerCase()}${number}@${domain}`;
}

export async function seedUsers(db: PrimaryDatabase): Promise<number> {
  const repository = await db.open(UserEntity);
  const users: UserEntity[] = [];

  for (let i = 0; i < 1000; i++) {
    const firstName = getRandomElement(firstNames);
    const lastName = getRandomElement(lastNames);
    const email = generateEmail(firstName, lastName);
    const isEmailVerified = Math.random() > 0.3; // 70% verified

    const user = new UserEntity();
    user.id = random.nanoid(15);
    user.email = email;
    user.name = `${firstName} ${lastName}`;
    user.firstName = firstName;
    user.lastName = lastName;
    user.isEmailVerified = isEmailVerified;
    user.image =
      Math.random() > 0.5
        ? `https://api.dicebear.com/7.x/avataaars/svg?seed=${firstName}${lastName}`
        : undefined;

    users.push(user);
  }

  await repository.save(users);
  return users.length;
}

